GPSlay32: Core/MyApp/App/admin.h File Reference
admin.h File Reference
Bevat de defines & externals voor deze applicatie.
#include "FreeRTOS.h"
#include "event_groups.h"
#include "queue.h"
#include "task.h"
#include "semphr.h"
#include "message_buffer.h"
#include "cmsis_os.h"
#include "stdio.h"
#include "string.h"
#include "stdlib.h"
#include "ctype.h"
Data Structures
struct TaskData
struct voor taak-gegevens, waaronder de argumenten om een taak aan te maken
Macros
#define ARMKEYS_DEBUG_OUT 0x02
bit 2: toggles armkeys stuff output
#define DEBUG_OUT_ALL 0xff
genereer alle test output
#define DEBUG_OUT_NONE 0x00
stop alle test output
#define FALSE 0
#define GPS_DEBUG_OUT 0x10
bit 5: toggles gps uart1 output
#define GPS_MAXLEN 79+4
#define LEDBLUE GPIO_PIN_15
LD6_Pin.
#define LEDGREEN GPIO_PIN_12
#define LEDORANGE GPIO_PIN_13
LD5_Pin.
#define LEDRED GPIO_PIN_14
LD3_Pin.
#define LEDS_DEBUG_OUT 0x01
bit 1: toggles leds stuff output
#define NRF24_DEBUG_OUT 0x40
bit 7: toggles NRF24 RX output
#define QSIZE_UART 10
set queue op 10 elementen
#define RES1_DEBUG_OUT 0x24
bit 6: toggles reserved2 output
#define STUDENT_DEBUG_OUT 0x08
bit 4: toggles student stuff output
#define TIMER1_DELAY 500
set software timer 500 msecs
#define TRUE 1
#define UART_DEBUG_OUT 0x04
bit 3: toggles uart2 stuff output
Typedefs
typedef struct TaskData * PTASKDATA
typedef struct TaskData TASKDATA
struct voor taak-gegevens, waaronder de argumenten om een taak aan te maken
Functions
void ARM_keys_IRQ (void *)
Deze task handelt de ARM-toets af, die ontvangen is van de ISR-handler (zie: stm32f4xx_it.c).
void ARM_keys_task (void *)
Task krijgt ARM-key met notificatie binnen, en zet ledjes op die waarde. Ook de gekleurde ledjes (behalve blauw, die wordt door de timer gebruikt) krijgen een schwung...
void CreateHandles (void)
Creates alle handles voor deze applicatie.
void CreateTasks (void)
Creëert alle taken door te scannen door de TASKDATA-argumenten-array.
Let op. Eerst wordt de scheduler gestopt, dan de taken gecreëerd, dan de scheduler gestopt. Waarom? Anders gaan taken gelijk beginnen en wachten op taken die nog niet bestaan, dat geeft een rommeltje.
void DisplayMenu (void)
void DisplayTaskData (void)
Displays de stack-gegevens van alle taken op de UART.
void DisplayVersion (void)
void error_HaltOS (char *)
Fatale OS-error opgetreden tijdens startup of runtime, doorgaan is zinloos. Het OS wordt tot stoppen gebracht, er wordt output gegenereerd waar mogelijk, dus op UART en LCD.
osThreadId_t GetTaskhandle (char *)
Zoekt in tasks-array de task, en returns de handle. Deze handle wordt door CreateTasks() in de array geplaatst. In plaats van deze functie kan ook de OS-functie xTaskGetHandle() gebruikt worden. Alleen is 'mijn' functie sneller.
void GPS_getNMEA (void *)
Leest de GPS-NMEA-strings die via de UART via interrupt-handler (HAL_UART_RxCpltCallback) binnenkomen. * De handler zet elk inkomende character gelijk op een queue, die hier uitgelezen wordt. Vervolgens wordt hiervan een GPS-message opgebouwd en verwerkt.
void GPS_parser (void *)
void LED_Task1 (void *)
Tasks die ledjes manipuleren nadat ze eerst afgeschermd zijn met mutex semaphores.
void LED_Task2 (void *)
Tasks die ledjes manipuleren nadat ze eerst afgeschermd zijn met mutex semaphores.
void LED_Task3 (void *)
Tasks die ledjes manipuleren nadat ze eerst afgeschermd zijn met mutex semaphores. Task 3 en 4 werken daarnaast nog met tasknotification.
void LED_Task4 (void *)
Tasks die ledjes manipuleren nadat ze eerst afgeschermd zijn met mutex semaphores. Task 3 en 4 werken daarnaast nog met tasknotification.
void NRF_Driver (void *)
Driver for the NRF24 module in receiver mode. Checks continously for new data.
void Route_Setter (void *)
Task that waits for a ARM key press to set a waypoint by calling the GPS_Route_Maker function, making a linkedlist of waypoints.
void SetTaskPriority (int, int)
Verandert de prioriteit van een taak. Eerst wordt de taak gezocht in de lijst van alle taken (tasks[]) Daarna wordt de priority in de lijst gewijzigd en prioriteit van de taak aangepast. De functie DisplayTaskData() toont op de UART het tasknummer dat je nodig hebt.
void StartStopTask (int)
Suspends (stopt) of Resumes (start) een task. Pas op. Als een task suspended wordt als hij een mutex bezet houdt blokkeer je alle tasks die op die mutex wachten. En als je de task stopt die de UART leest, schiet je jezelf ook in de voet.
void Student_task1 (void *)
Oefentask voor studenten.
void Timer1_Handler (void)
Vangt de FreeRTOS software-interrupt op en toggelt een ledje.
void UART_keys_IRQ (void *)
Leest characters in die de gebruiker via Terminalprogramma intikt.
void UART_keys_poll (void *)
deze waarde kan hier veranderd worden.
void UART_menu (void *)
User Interface. De task wacht op kant en klare user-strings (TaskNotifyTake) van ISR-handler, en interpreteert de string. Het eerste character geeft het hoofd-commando aan. Afhankelijk van het commando worden opvolgende chars geinterpreteerd.
Variables
SemaphoreHandle_t hGPS_Mutex
handle voor GPS parser Mutex
QueueHandle_t hGPS_Queue
handle voor GPS-queue
EventGroupHandle_t hKEY_Event
handle voor ARM-keys-event
SemaphoreHandle_t hLED_Sem
handle voor LED-mutex
TimerHandle_t hTimer1
handle voor software timer
QueueHandle_t hUART_Queue
typedefs of struct itself and pointer to it
char NRF24_new_value
NRF24 status bits.
int Uart_debug_out
default: debug all output to uart
Detailed Description
Bevat de defines & externals voor deze applicatie.
Attention
© Copyright (c) 2021 (HU) Michiel Scager.
Author
MSC
Date
5/5/2022
Definition in file admin.h.
Macro Definition Documentation
ARMKEYS_DEBUG_OUT
#define ARMKEYS_DEBUG_OUT 0x02
bit 2: toggles armkeys stuff output
Definition at line 79 of file admin.h.
Referenced by ARM_keys_task(), and UART_menu().
DEBUG_OUT_ALL
#define DEBUG_OUT_ALL 0xff
genereer alle test output
Definition at line 71 of file admin.h.
Referenced by UART_menu().
DEBUG_OUT_NONE
#define DEBUG_OUT_NONE 0x00
stop alle test output
Definition at line 69 of file admin.h.
Referenced by UART_menu().
FALSE
#define FALSE 0
Definition at line 24 of file admin.h.
Referenced by GPS_getNMEA(), and UART_keys_IRQ().
GPS_DEBUG_OUT
#define GPS_DEBUG_OUT 0x10
bit 5: toggles gps uart1 output
Definition at line 85 of file admin.h.
Referenced by fill_GNRMC(), GPS_getNMEA(), and UART_menu().
GPS_MAXLEN
#define GPS_MAXLEN 79+4
Definition at line 32 of file admin.h.
Referenced by CreateHandles(), and GPS_getNMEA().
LEDBLUE
#define LEDBLUE GPIO_PIN_15
LD6_Pin.
Definition at line 102 of file admin.h.
LEDGREEN
#define LEDGREEN GPIO_PIN_12
Redefine pins om beter aan te geven waar het om gaat: gekleurde ledjes LD4_Pin
Definition at line 96 of file admin.h.
Referenced by ARM_keys_task(), and fill_GNRMC().
LEDORANGE
#define LEDORANGE GPIO_PIN_13
LD5_Pin.
Definition at line 100 of file admin.h.
Referenced by ARM_keys_task().
LEDRED
#define LEDRED GPIO_PIN_14
LD3_Pin.
Definition at line 98 of file admin.h.
Referenced by ARM_keys_task().
LEDS_DEBUG_OUT
#define LEDS_DEBUG_OUT 0x01
bit 1: toggles leds stuff output
Definition at line 77 of file admin.h.
Referenced by LED_Task1(), LED_Task2(), LED_Task3(), LED_Task4(), and UART_menu().
NRF24_DEBUG_OUT
#define NRF24_DEBUG_OUT 0x40
bit 7: toggles NRF24 RX output
Definition at line 89 of file admin.h.
Referenced by NRF_receive(), and UART_menu().
QSIZE_UART
#define QSIZE_UART 10
set queue op 10 elementen
Definition at line 27 of file admin.h.
Referenced by CreateHandles(), UART_keys_IRQ(), and UART_keys_poll().
RES1_DEBUG_OUT
#define RES1_DEBUG_OUT 0x24
bit 6: toggles reserved2 output
Definition at line 87 of file admin.h.
STUDENT_DEBUG_OUT
#define STUDENT_DEBUG_OUT 0x08
bit 4: toggles student stuff output
Definition at line 83 of file admin.h.
Referenced by Student_task1(), and UART_menu().
TIMER1_DELAY
#define TIMER1_DELAY 500
set software timer 500 msecs
Definition at line 30 of file admin.h.
Referenced by CreateHandles().
TRUE
#define TRUE 1
Definition at line 23 of file admin.h.
Referenced by ARM_keys_task(), error_HaltOS(), GPS_getNMEA(), LED_Task1(), LED_Task2(), LED_Task3(), LED_Task4(), NRF_Driver(), Route_Setter(), Student_task1(), UART_keys_IRQ(), UART_keys_poll(), and UART_menu().
UART_DEBUG_OUT
#define UART_DEBUG_OUT 0x04
bit 3: toggles uart2 stuff output
Definition at line 81 of file admin.h.
Referenced by UART_keys_IRQ(), UART_keys_poll(), and UART_menu().
Typedef Documentation
PTASKDATA
typedef struct TaskData * PTASKDATA
TASKDATA
typedef struct TaskData TASKDATA
struct voor taak-gegevens, waaronder de argumenten om een taak aan te maken
The carriage return [CR] and the line feed [LF] combination terminate the sentence. NMEA 0 83 sentences vary in length, but each sentence is limited to 79 characters or less. This length limit excludes the $ and the [CR][LF] characters. The data field block, including delimiters is limited to 74 characters or less.
Function Documentation
ARM_keys_IRQ()
void ARM_keys_IRQ (void * argument) extern
Deze task handelt de ARM-toets af, die ontvangen is van de ISR-handler (zie: stm32f4xx_it.c).
Parameters
*argument Niet gebruikt, eventueel een waarde of string om te testen
Returns
void.
Definition at line 36 of file ARM_keys.c.
{
    unsigned int key;
    osThreadId_t hTask;
    UART_puts("\r\n"); UART_puts((char *)__func__); UART_puts(" started");
    if (!(hTask = xTaskGetHandle("ARM_keys_task")))
        error_HaltOS("Err:ARM_hndle");
    while (1)
    {
        // wait for ISR (EXTI0_IRQHandler()) to signal that a key is pressed
        key = xEventGroupWaitBits(hKEY_Event, 0xffff, pdTRUE, pdFALSE, portMAX_DELAY );
        xTaskNotify(hTask, key, eSetValueWithOverwrite); // notify task2 with value
    }
}
References error_HaltOS(), and hKEY_Event.
ARM_keys_task()
void ARM_keys_task (void * argument) extern
Task krijgt ARM-key met notificatie binnen, en zet ledjes op die waarde. Ook de gekleurde ledjes (behalve blauw, die wordt door de timer gebruikt) krijgen een schwung...
Parameters
*argument Niet gebruikt, eventueel een waarde of string om te testen.
Returns
void.
Definition at line 63 of file ARM_keys.c.
{
    uint32_t     key;
    int          i, led;
    while(TRUE)
    {
        // WAITING FOR users key
        xTaskNotifyWait (0x00,              // Don't clear any notification bits on entry.
                         0xffffffff,        // ULONG_MAX, reset the notification value to 0 on exit.
                         &key,              // Notified value.
                         portMAX_DELAY);    // Block indefinitely.
        xSemaphoreTake(hLED_Sem, portMAX_DELAY); // krijg toegang (mutex) tot leds
        LED_put((unsigned char)key); // set 8 leds-byte to key-value
        BUZZER_put (500);
        osDelay(500);
        UART_puts("\r\n\tARM_key pressed to leds: "); UART_putint(key);
        if (Uart_debug_out & ARMKEYS_DEBUG_OUT)
        {
            UART_puts("\r\n\tARM_key pressed to leds: "); UART_putint(key);
        }
        xSemaphoreGive(hLED_Sem); // geef toegang (mutex) vrij
        // tot slot, laat de gekleurde ledjes meedoen
        // maar niet blauw, want die is ingezet voor de timer
        // kijk naar de manier waarop de if-elses er uitzien
        for (i=0; i<3; i++)
        {
            led = (i==0 ? LEDRED : (i==1 ? LEDORANGE : LEDGREEN));
            toggle_led(led);
        }
        // Also notify the Route_Setter task so it can act on this key press.
        // Using a direct task notification avoids races that happen when multiple
        // consumers try to read the shared event group bits.
        osThreadId_t hRoute = GetTaskhandle("Route_setter");
        if (hRoute)
        {
            xTaskNotify(hRoute, key, eSetValueWithOverwrite);
        }
        taskYIELD(); // done, force context switch
    }
}
References ARMKEYS_DEBUG_OUT, GetTaskhandle(), hLED_Sem, LEDGREEN, LEDORANGE, LEDRED, toggle_led(), TRUE, and Uart_debug_out.
CreateHandles()
void CreateHandles (void) extern
Creates alle handles voor deze applicatie.
Returns
void
Definition at line 220 of file admin.c.
{
    if (!(hLED_Sem = xSemaphoreCreateMutex()))
        error_HaltOS("Error hLED_Sem");
    if (!(hUART_Queue = xQueueCreate(QSIZE_UART, sizeof(unsigned int))))
        error_HaltOS("Error hUART_Q");
    if (!(hGPS_Queue = xQueueCreate(GPS_MAXLEN, sizeof(unsigned char))))
        error_HaltOS("Error hGPS_Q");
    if (!(hKEY_Event = xEventGroupCreate()))
        error_HaltOS("Error hLCD_Event");
    if (!(hTimer1 = xTimerCreate("Timer_1", pdMS_TO_TICKS(TIMER1_DELAY), pdTRUE, 0, (TimerCallbackFunction_t)Timer1_Handler)))
        error_HaltOS("Error hTimer1");
    if (!(hGPS_Mutex = xSemaphoreCreateMutex()))
        error_HaltOS("Error hGPS_Mutex");
    UART_puts("\n\rAll handles created successfully.");
    UART_puts("\n\rTimer set to: ");
    UART_putint((int)TIMER1_DELAY); // (int)-cast is nodig!
    xTimerStart(hTimer1, 0); // start de timer...
}
References error_HaltOS(), GPS_MAXLEN, hGPS_Mutex, hGPS_Queue, hKEY_Event, hLED_Sem, hTimer1, hUART_Queue, QSIZE_UART, TIMER1_DELAY, and Timer1_Handler().
Referenced by StartDefaultTask().
CreateTasks()
void CreateTasks (void) extern
Creëert alle taken door te scannen door de TASKDATA-argumenten-array.
Let op. Eerst wordt de scheduler gestopt, dan de taken gecreëerd, dan de scheduler gestopt. Waarom? Anders gaan taken gelijk beginnen en wachten op taken die nog niet bestaan, dat geeft een rommeltje.
Remarks
DEEL 3 van admin.c Bevat de functies voor het creëren van tasks en admin-functies voor tasks
Returns
void
Definition at line 277 of file admin.c.
{
    PTASKDATA ptd = tasks; // tasks == &tasks[0]: both are addresses of first struct
    vTaskSuspendAll(); // zet de scheduler stil en dwing FreeRTOS om eerst alle taken te starten
    for (; ptd->func != NULL; ptd++) // loopje zonder teller; gewoon de pointer steeds ophogen...
    {
        UART_puts("\r\nCreated: ");
        UART_puts((char *)ptd->attr.name);
        // nb. kijk naar de haakjes van argument 3: het gaat om het adres van (structure attr).
        ptd->hTask = osThreadNew(ptd->func, ptd->argument, &(ptd->attr));
    }
    UART_puts("\r\n");
    xTaskResumeAll();   // start nu de scheduler: play ball
    DisplayTaskData();  // display alle taskdata op UART
}
References TaskData::argument, TaskData::attr, DisplayTaskData(), TaskData::func, TaskData::hTask, and tasks.
Referenced by StartDefaultTask().
DisplayMenu()
void DisplayMenu (void) extern
User Interface (menu) naar UART.
Returns
void
Author
MSC
Definition at line 162 of file admin.c.
{
    char *menu =
"\r\n\
Menu:===============================================================\r\n\
key: function\r\n\
 0 : [on/off] ALL TEST OUTPUT\r\n\
 1 : [on/off] LEDS output\r\n\
 2 : [on/off] ARM_keys output\r\n\
 3 : [on/off] UART_keys output\r\n\
 4 : [on/off] STUDENT output\r\n\
 5 : [on/off] GPS output\r\n\
 d : change DELAY time (default 200), eg. 'd,50'\r\n\
 p : change TASK PRIORITY, eg. 'p,7,20' sets priority of task 7 to 20\r\n\
 t : display TASK DATA (number, priority, stack usage, status)\r\n\
 s : start/stop TASK, eg. s,7 starts or stops task 7\r\n\
=====================================================================\r\n";
    UART_puts(menu);
}
Referenced by DisplayVersion(), and UART_menu().
DisplayTaskData()
void DisplayTaskData (void) extern
Displays de stack-gegevens van alle taken op de UART.
Returns
void
Definition at line 387 of file admin.c.
{
    PTASKDATA    ptd = tasks;
    UBaseType_t  highwatermark;
    TaskStatus_t xTaskDetails;
    unsigned int free, totalalloc = 0;
    unsigned int task_nr; // tasknr for changing priority
    for (task_nr=1; ptd->func != NULL; ptd++, task_nr++)
    {
        highwatermark = uxTaskGetStackHighWaterMark(ptd->hTask);   // amount of free bytes
        free = (highwatermark * 100) / ptd->attr.stack_size;        // in percentage
        totalalloc += ptd->attr.stack_size;
        vTaskGetInfo (ptd->hTask, &xTaskDetails, pdTRUE, eInvalid); // get task status
        UART_puts("\r\n\t[");        UART_putint(task_nr); UART_puts("] ");
        UART_puts(ptd->attr.name);
        UART_puts("\t priority: ");  UART_putint(ptd->attr.priority);
        UART_puts("\t stacksize: "); UART_putint(ptd->attr.stack_size * 4);
        UART_puts("\t free: ");  UART_putint(highwatermark*4);
        UART_puts("\t used: ");      UART_putint(100 - free); UART_puts("%");
        UART_puts("\t status: ");    UART_puts(xTaskDetails.eCurrentState == eSuspended ? "suspended": "running");
    }
    UART_puts("\r\n\tTotal heap: "); UART_putint(configTOTAL_HEAP_SIZE);
    UART_puts("    Allocated task stack: "); UART_putint(totalalloc * 4);
    UART_puts("    Free heap space: "); UART_putint(configTOTAL_HEAP_SIZE - (totalalloc * 4));
    UART_puts("\r\n");
}
References TaskData::attr, TaskData::func, TaskData::hTask, and tasks.
Referenced by CreateTasks(), and UART_menu().
DisplayVersion()
void DisplayVersion (void) extern
Remarks
DEEL 1 van admin.c Bevat de functies voor de initialisatie output, vooral naar UART, zoals het 'menu' Schrijft applicatiedata (versie, werking, menu) naar UART. Les: je ziet hoe je handig een lange string kunt opstellen met het '\'-karakter.
Returns
void
Author
MSC
Definition at line 126 of file admin.c.
{
    char infobuf[100];
    osVersion_t osv;
    char *functionality =
"Deze applicatie laat verschillende FreeRTOS-mechanismen zien, zoals \r\n\
queues, notifications, eventgroups, mutex-semaphores, message-buffers, interrupt handling \r\n\
en hoe je makkelijk tasks aanmaakt (admin.c) en hoe je de bidirectionele omgang \r\n\
met de UART-comport gebruikt.\r\n\
Zie verder de Doxygen documentatie van de applicatie.\r\n\
Michiel Scager (update: april 2023)\r\n";
    LCD_clear();
    LCD_puts(app_nameLCD);
    UART_puts(app_name);
    UART_puts(functionality);
    osKernelGetInfo(&osv, infobuf, sizeof(infobuf));
    UART_puts("\t-----");
    UART_puts("\r\n\t");                       UART_puts(infobuf);
    UART_puts("\r\n\tVersion: ");              UART_putint(osv.kernel);
    UART_puts("\r\n\tOS Timer freq (MHz): " ); UART_putint(osKernelGetSysTimerFreq()/1000000);
    UART_puts("\r\n\tOS Tick freq (Hz): " );   UART_putint(osKernelGetTickFreq());
    UART_puts("\r\n\t-----\r\n");
    DisplayMenu();
}
References app_name, app_nameLCD, and DisplayMenu().
Referenced by main().
error_HaltOS()
void error_HaltOS (char * msg) extern
Fatale OS-error opgetreden tijdens startup of runtime, doorgaan is zinloos. Het OS wordt tot stoppen gebracht, er wordt output gegenereerd waar mogelijk, dus op UART en LCD.
Remarks
DEEL 2 van admin.c Bevat de functies voor het creëren van alle handles
Parameters
msg Foutmelding
Returns
void
Definition at line 202 of file admin.c.
{
    LCD_puts(msg);
    UART_puts(msg); UART_puts(". Application halted\r\n");
    BUZZER_put(1000);
    vTaskSuspendAll(); // stop alle tasks
    while (TRUE)
    {
    }
}
References TRUE.
Referenced by ARM_keys_IRQ(), CreateHandles(), fill_GNRMC(), getlatest_GNRMC(), LED_Task3(), LED_Task4(), and UART_keys_IRQ().
GetTaskhandle()
osThreadId_t GetTaskhandle (char * taskname) extern
Zoekt in tasks-array de task, en returns de handle. Deze handle wordt door CreateTasks() in de array geplaatst. In plaats van deze functie kan ook de OS-functie xTaskGetHandle() gebruikt worden. Alleen is 'mijn' functie sneller.
Parameters
*taskname De tasknaam
Returns
osThreadId_t De taskhandle
Definition at line 304 of file admin.c.
{
    PTASKDATA ptd = tasks;
    for (; ptd->func != NULL; ptd++)
        if (!strcmp(taskname, ptd->attr.name))
            return (ptd->hTask);
    return (NULL); // if task was not found...
}
References TaskData::attr, TaskData::func, TaskData::hTask, and tasks.
Referenced by ARM_keys_task().
GPS_getNMEA()
void GPS_getNMEA (void * argument) extern
Leest de GPS-NMEA-strings die via de UART via interrupt-handler (HAL_UART_RxCpltCallback) binnenkomen. * De handler zet elk inkomende character gelijk op een queue, die hier uitgelezen wordt. Vervolgens wordt hiervan een GPS-message opgebouwd en verwerkt.
Returns
void
Definition at line 127 of file gps.c.
{
    char  Q_char;               // char to receive from queue
    char  MSG_buff[GPS_MAXLEN]; // buffer for GPS-string
    int   pos = 0;
    int   cs;                   // checksum-flag
    int   new_msg = FALSE;      // do we encounter a '$'-char?
    int   msg_type = 0;         // do we want this message to be interpreted?
    UART_puts((char *)__func__); UART_puts("started\n\r");
    while (TRUE)
    {
        xQueueReceive(hGPS_Queue, &Q_char, portMAX_DELAY); // get one char from the q
        //UART_putchar(Q_buff);  // echo, for testing
        if (Q_char == '$') // gotcha, new datastring started
        {
            memset(MSG_buff, 0, sizeof(MSG_buff)); // clear buff
            pos = 0;
            new_msg = TRUE; // from now on, chars are valid to receive
        }
        if (new_msg == FALSE) // char only valid if started by $
            continue;
        MSG_buff[pos] = Q_char; // copy char read from Q into the msg-buf
        // if pos==5, the message type (f.i. "$GPGSA) is complete, so we now we can determine
        // if we want the rest of the message... else we skip the rest characters
        if (pos == 5)
        {
            msg_type = 0; // reset
            // next, we decide which message types we want to interpret
            // and we set the message-type for later use...
            if      (!strncmp(&MSG_buff[1], "GNRMC", 5)) msg_type = eGNRMC;
            else if (!strncmp(&MSG_buff[1], "GPGSA", 5)) msg_type = eGPGSA;
            else if (!strncmp(&MSG_buff[1], "GNGGA", 5)) msg_type = eGNGGA;
            if (!msg_type) // not an interesting message type
            {
                new_msg = FALSE;
                continue;
            }
        }
        // if we are here, we are reading the rest of the message into the msg_buff
        if (pos >= GPS_MAXLEN - 1) // avoid overflow (should not happen, but still...)
        {
            new_msg = FALSE; // ignore it
            continue;
        }
        if (MSG_buff[pos] == '\r') // end of message encountered - all messages end with <CR-13><LF-10>
        {
            MSG_buff[pos] = '\0';          // close string
            cs = checksum_valid(MSG_buff); // note, checksumchars (eg "*43") are removed from string
            if (Uart_debug_out & GPS_DEBUG_OUT) // output to uart if wanted
            {
                UART_puts("\r\nGPS (UART4): "); UART_puts(MSG_buff);
                UART_puts( cs ? " [cs:OK]\r\n" : " [cs:ERR]\r\n");
            }
            if (cs) // checksum okay, so interpret the message
            {
                switch(msg_type) // extract data from msg into right struct
                {
                case eGNRMC: fill_GNRMC(MSG_buff);
                             // use the data...
                             break;
                case eGPGSA:
                case eGNGGA: break;
                default:     break;
                }
            }
            new_msg = FALSE; // new message possible
            continue;
        }
        pos++; // proceed reading next char from the queue
    }
}
References checksum_valid(), eGNGGA, eGNRMC, eGPGSA, FALSE, fill_GNRMC(), GPS_DEBUG_OUT, GPS_MAXLEN, hGPS_Queue, TRUE, and Uart_debug_out.
GPS_parser()
void GPS_parser (void *) extern
LED_Task1()
void LED_Task1 (void * argument) extern
Tasks die ledjes manipuleren nadat ze eerst afgeschermd zijn met mutex semaphores.
Parameters
*argument Niet gebruikt, eventueel een waarde of string om te testen
Returns
void
Definition at line 44 of file ledjes.c.
{
    UART_puts((char *)__func__); UART_puts(" started\r\n");
    int i, leds;
    while(TRUE)
    {
        xSemaphoreTake(hLED_Sem, portMAX_DELAY); /* wacht op toegang tot de semaphore;
        * de code hieronder wordt alleen uitgevoerd nadat ik de mutex heb gekregen.
        * andere tasks die op deze mutex wachten, kunnen pas door nadat ik de mutex
        * heb vrijgegeven met Give.
        */
        leds = 128; // start at led nr. 8
        for (i=0; i<8; i++, leds>>=1)
        {
            LED_put(leds); // set leds
            osDelay(os_delay);
            if (Uart_debug_out & LEDS_DEBUG_OUT)
            {
                UART_puts("\r\nM1 led: "); UART_putint(leds);
            }
        }
        xSemaphoreGive(hLED_Sem); // geef de semaphore weer vrij voor een ander
        taskYIELD(); // done, force context switch, otherwise freeRTOS stays in this task
    }
}
References hLED_Sem, LEDS_DEBUG_OUT, os_delay, TRUE, and Uart_debug_out.
LED_Task2()
void LED_Task2 (void * argument) extern
Tasks die ledjes manipuleren nadat ze eerst afgeschermd zijn met mutex semaphores.
Parameters
*argument Niet gebruikt, eventueel een waarde of string om te testen
Returns
void
Definition at line 77 of file ledjes.c.
{
    UART_puts((char *)__func__); UART_puts(" started\r\n");
    int i, leds;
    while(TRUE)
    {
        xSemaphoreTake(hLED_Sem, portMAX_DELAY); // wait to enter
        leds = 1;
        for (i=0; i<8; i++, leds<<=1)
        {
            LED_put(leds); // set leds
            osDelay(os_delay);
            if (Uart_debug_out & LEDS_DEBUG_OUT)
            {
                UART_puts("\r\n\tM2 led: "); UART_putint(leds);
            }
        }
        xSemaphoreGive(hLED_Sem); // free mutex
        taskYIELD(); // done, force context switch, otherwise freeRTOS stays in this task
    }
}
References hLED_Sem, LEDS_DEBUG_OUT, os_delay, TRUE, and Uart_debug_out.
LED_Task3()
void LED_Task3 (void * argument) extern
Tasks die ledjes manipuleren nadat ze eerst afgeschermd zijn met mutex semaphores. Task 3 en 4 werken daarnaast nog met tasknotification.
Parameters
*argument Niet gebruikt, eventueel een waarde of string om te testen
Returns
void
Definition at line 107 of file ledjes.c.
{
    int          i, leds;
    osThreadId_t hTask4;
    if (!(hTask4 = xTaskGetHandle("LED_Task4")))
       error_HaltOS("Err:hTask4");
    UART_puts((char *)__func__); UART_puts(" started\r\n");
    while(TRUE)
    {
        xSemaphoreTake(hLED_Sem, portMAX_DELAY); // wait to get in...
        for (i=0; i<4; i++) // voorbeeld hoe je je code zo overdraagbaar mogelijk maakt
        {
            if      (i==0)  leds = 8+16; // zichtbaar: 1. waarde i, 2. welke leds aan gaan
            else if (i==1)  leds = 4+32; // ... had ook met switch-case gekund
            else if (i==2)  leds = 2+64;
            else            leds = 1+128;
            LED_put(leds);     // set leds
            osDelay(os_delay); // snelheid bepalen, kan veranderd worden via user interface
            if (Uart_debug_out & LEDS_DEBUG_OUT)
            {
                UART_puts("\r\n\t\tM3 led: "); UART_putint(leds);
            }
        }
        xSemaphoreGive(hLED_Sem); // free mutex
        xTaskNotifyGive(hTask4); // give the ball to mutextask4
        osDelay(200);
        ulTaskNotifyTake(pdTRUE, portMAX_DELAY); // wait for task 4
    }
}
References error_HaltOS(), hLED_Sem, LEDS_DEBUG_OUT, os_delay, TRUE, and Uart_debug_out.
LED_Task4()
void LED_Task4 (void * argument) extern
Tasks die ledjes manipuleren nadat ze eerst afgeschermd zijn met mutex semaphores. Task 3 en 4 werken daarnaast nog met tasknotification.
Parameters
*argument Niet gebruikt, eventueel een waarde of string om te testen
Returns
void
Definition at line 152 of file ledjes.c.
{
    int          i, leds;
    osThreadId_t hTask3;
    if (!(hTask3 = xTaskGetHandle("LED_Task3")))
       error_HaltOS("Err:hTask3");
    UART_puts((char *)__func__); UART_puts(" started\r\n");
    while(TRUE)
    {
        ulTaskNotifyTake(pdTRUE, portMAX_DELAY); // wait for notification
        xSemaphoreTake(hLED_Sem, portMAX_DELAY); // wait for mutex
        for (i=0; i<4; i++) // voorbeeld hoe je je code zo overdraagbaar mogelijk maakt
        {
            if      (i==0)  leds = 1+128; // zichtbaar: 1. waarde i, 2. welke leds aan gaan
            else if (i==1)  leds = 2+64;  // had ook met switch-case gekund, maar dit is korter...
            else if (i==2)  leds = 4+32;
            else            leds = 8+16;
            LED_put(leds);     // set leds
            osDelay(os_delay); // snelheid bepalen, waarde os_delay kan veranderd worden via user interface
            if (Uart_debug_out & LEDS_DEBUG_OUT)
            {
                UART_puts("\r\n\t\t\tM4 led: "); UART_putint(leds);
            }
        }
        xSemaphoreGive(hLED_Sem); // free mutex
        osDelay(200);
        xTaskNotifyGive(hTask3); // give the ball back to task 3
    }
}
References error_HaltOS(), hLED_Sem, LEDS_DEBUG_OUT, os_delay, TRUE, and Uart_debug_out.
NRF_Driver()
void NRF_Driver (void * argument) extern
Driver for the NRF24 module in receiver mode. Checks continously for new data.
Parameters
argument
Definition at line 33 of file NRF_driver.c.
{
    osDelay(100);
    UART_puts((char *)__func__); UART_puts(" started\r\n");
    uint8_t addr[5] = {0xE7, 0xE7, 0xE7, 0xE7, 0xE7};
    HAL_GPIO_WritePin(ce_gpio_port, ce_gpio_pin, 0); // Set CE low
    HAL_GPIO_WritePin(csn_gpio_port, csn_gpio_pin, 1); // Set CSN high
    nrf24_init(); // Initialize NRF24L01+
    nrf24_tx_pwr(_0dbm); // Set TX power to 0dBm
    nrf24_data_rate(_1mbps); // Set data rate to 1Mbps
    nrf24_set_channel(78); // Set channel to 76
    nrf24_pipe_pld_size(0, PLD_SIZE); // Set payload size for pipe 0
    nrf24_set_crc(en_crc, _1byte); // Enable CRC with 1 byte
    nrf24_open_rx_pipe(0, addr); // Open TX pipe with address
    nrf24_pwr_up(); // Power up the NRF24L01+
    while (TRUE)
    {
        NRF_receive();
        osDelay(1); // Placeholder delay
    }
}
References NRF_receive(), PLD_SIZE, and TRUE.
Route_Setter()
void Route_Setter (void * argument) extern
Task that waits for a ARM key press to set a waypoint by calling the GPS_Route_Maker function, making a linkedlist of waypoints.
Parameters
argument
Definition at line 226 of file GPS_Route_Setter.c.
{
    //Create a key variable to store the key pressed by the user
    uint32_t key=0;
    while(TRUE){
        // Wait for a notification from the ARM key handler.
        xTaskNotifyWait(0x00,            // Don't clear any notification bits on entry
                        0xffffffff,      // Clear the notification value on exit
                        &key,            // Notified value
                        portMAX_DELAY);  // Block indefinitely
        UART_puts("\r\n");
        switch(key){
        case 0x01: // key 1 pressed (upper left)
            #ifdef debug_routesetter
                UART_puts("\r\n");
                UART_puts("Trying to set a waypoint...");
                UART_puts("\r\n");
            #endif
            getlatest_GNRMC(&GNRMC_localcopy3);
            GPS_Route_Maker(); // Creates a node for a linked list everytime the ARM key is pressed
            break;
        case 0x02: // remove last node
            UART_puts("Removing last node...");
            Remove_Last_Node();
            break;
        case 0x03: // remove all nodes
            UART_puts("Removing all nodes...");
            while(Remove_Last_Node() != 0);
            break;
        case 0x04:
        UART_puts("Viewing all items in linked list...");
            View_Linkedlist();
            break;
        default: // incease a unassigned key is pressed
            UART_puts("Current key: "); UART_putint(key);
            UART_puts(" is not in use by GPS_Route_Setter.c");
            UART_puts("\r\n");
            break;
        }
        osDelay(1);
    }
}
References getlatest_GNRMC(), GNRMC_localcopy3, GPS_Route_Maker(), Remove_Last_Node(), TRUE, and View_Linkedlist().
SetTaskPriority()
void SetTaskPriority (int task_id, int new_priority) extern
Verandert de prioriteit van een taak. Eerst wordt de taak gezocht in de lijst van alle taken (tasks[]) Daarna wordt de priority in de lijst gewijzigd en prioriteit van de taak aangepast. De functie DisplayTaskData() toont op de UART het tasknummer dat je nodig hebt.
Parameters
task_id Task identifier
new_priority Nieuwe prioriteit
Returns
void
Definition at line 325 of file admin.c.
{
    PTASKDATA ptd = tasks;
    unsigned int    task_nr;
    for (task_nr = 1; ptd->func != NULL; ptd++, task_nr++)
        if (task_nr == task_id) // hebbes
        {
            ptd->attr.priority = new_priority;          // struct-member
            vTaskPrioritySet(ptd->hTask, new_priority); // taskpriority
            // of
            // osThreadSetPriority(ptd->hTask, new_priority);
            UART_puts("\r\nSet task "); UART_puts(ptd->attr.name);
            UART_puts("'s priority to: "); UART_putint(new_priority);
            return;
        }
}
References TaskData::attr, TaskData::func, TaskData::hTask, and tasks.
Referenced by UART_menu().
StartStopTask()
void StartStopTask (int task_id) extern
Suspends (stopt) of Resumes (start) een task. Pas op. Als een task suspended wordt als hij een mutex bezet houdt blokkeer je alle tasks die op die mutex wachten. En als je de task stopt die de UART leest, schiet je jezelf ook in de voet.
Returns
void
Definition at line 353 of file admin.c.
{
    PTASKDATA ptd = tasks;
    unsigned int    task_nr;
    TaskStatus_t    xTaskDetails;
    for (task_nr = 1; ptd->func != NULL; ptd++, task_nr++)
        if (task_nr == task_id) // hebbes
        {
            vTaskGetInfo (ptd->hTask, &xTaskDetails, pdTRUE, eInvalid);
            UART_puts("\r\n");
            UART_puts(ptd->attr.name);
            // een task kan meerdere statussen hebben; het wordt simpeler
            // als je alleen de eSuspended checkt.
            if (xTaskDetails.eCurrentState == eSuspended)
            {
                vTaskResume(ptd->hTask);
                UART_puts(" resumed.");
            }
            else // bv. eBlocked, eRunning, eInvalid etc.
            {
                vTaskSuspend(ptd->hTask);
                UART_puts(" suspended.");
            }
            return;
        }
}
References TaskData::attr, TaskData::func, TaskData::hTask, and tasks.
Referenced by UART_menu().
Student_task1()
void Student_task1 (void * argument) extern
Oefentask voor studenten.
Parameters
argument,kan evt vanuit tasks gebruikt worden
Returns
void
Definition at line 19 of file student.c.
{
    UART_puts((char *)__func__); UART_puts(" started\r\n");
    char buf[80];
    unsigned int i = 0;
    while(TRUE)
    {
        osDelay(1000);
        if (Uart_debug_out & STUDENT_DEBUG_OUT)
        {
            sprintf(buf, "\r\n%s: %u", __func__, i++);
            UART_puts(buf);
        }
    }
}
References STUDENT_DEBUG_OUT, TRUE, and Uart_debug_out.
Timer1_Handler()
void Timer1_Handler (void) extern
Vangt de FreeRTOS software-interrupt op en toggelt een ledje.
Parameters
hTimer1 De handle van de timer
Returns
void
Definition at line 252 of file admin.c.
{
    // HAL_GPIO_TogglePin(GPIOD, LEDBLUE);   // turns led on/off
}
Referenced by CreateHandles().
UART_keys_IRQ()
void UART_keys_IRQ (void * argument) extern
Leest characters in die de gebruiker via Terminalprogramma intikt.
wacht op chars in queue, gevuld door de IRQ_handler (main.c)
notifies/stuurt command-string naar andere task
Parameters
*argument Niet gebruikt, eventueel een waarde of string om te testen
Returns
void
Definition at line 62 of file UART_keys.c.
{
    char            buffer[QSIZE_UART];
    char            buffer_copy[QSIZE_UART];
    int             pos = 0;
    int             finish = FALSE;
    osThreadId_t    hTask;
    UART_puts((char *)__func__); UART_puts("started, enter key on terminal...\r\n");
    if (!(hTask = xTaskGetHandle("UART_menu")))
        error_HaltOS("Err:UART_hndl 0");
    while(TRUE)
    {
        // laat de VIC de q vullen, die per char in onze eigen string geplaatst wordt
        // tot LFEED gedrukt is of qsize-1 bereikt is.
        // nb: argument 2 is het adres waar ik het q-char in zet
        // nb: q-receive haalt gelijk de buffer leeg (q-peek niet).
        xQueueReceive(hUART_Queue, &buffer[pos], portMAX_DELAY);
        // negeer dit char bij geen data: -1, 255, of CR of spatie
        if (buffer[pos] == 0 || buffer[pos] == -1 || buffer[pos] == 255 || buffer[pos] == CRETURN || buffer[pos] == 32)
            continue;
        //UART_putchar(buffer[pos]);  // echo
        // check of de string gesloten was of gesloten moet worden...
        if (buffer[pos] == LFEED)     // close als LF gedrukt
        {
            buffer[pos] = '\0';
            finish = TRUE;
        }
        else if (pos == QSIZE_UART - 2) // close if end of buf
        {
            buffer[++pos] = '\0';       // first, skip to last position, then close string
            finish = TRUE;
        }
        if (finish)
        {
            // de volgende taak krijgt een copy van de string
            // mijn eigen buffer kan zo gelijk weer gevuld worden door de ISR
            strcpy(buffer_copy, buffer);
            memset(buffer, 0, QSIZE_UART); // clear original buffer
            finish = FALSE;
            pos = 0;
            xTaskNotify(hTask, buffer_copy, eSetValueWithOverwrite); // notify task2 with copy
            //hello test
            if (Uart_debug_out & UART_DEBUG_OUT)
            {
                UART_puts("\n\r"); UART_puts((char *)__func__);
                UART_puts(": UART_menu notified with "); UART_puts(buffer_copy);
                UART_puts("\r\n");
            }
        }
        else
            pos++;
    }
}
References error_HaltOS(), FALSE, hUART_Queue, QSIZE_UART, TRUE, UART_DEBUG_OUT, and Uart_debug_out.
UART_keys_poll()
void UART_keys_poll (void * argument) extern
deze waarde kan hier veranderd worden.
Polt en leest characters in die de gebruiker via Terminalprogramma intikt.
leest characters van uart
notifies command-string naar andere task
Parameters
*argument Niet gebruikt, eventueel een waarde of string om te testen
Returns
void
Definition at line 31 of file UART_keys.c.
{
    char buffer[QSIZE_UART];
    osThreadId_t hTask = xTaskGetHandle("UART_menu");
    UART_puts((char *)__func__); UART_puts("started, enter key on terminal\n\r");
    while(TRUE)
    {
        UART_gets(buffer, QSIZE_UART, TRUE); // wait for string
        xTaskNotify(hTask, buffer, eSetValueWithOverwrite); // notify task2 with value
        if (Uart_debug_out & UART_DEBUG_OUT)
        {
            UART_puts("\n\r"); UART_puts((char *)__func__);
            UART_puts("- notified with "); UART_puts(buffer);
            UART_puts("\r\n");
        }
    }
}
References QSIZE_UART, TRUE, UART_DEBUG_OUT, and Uart_debug_out.
UART_menu()
void UART_menu (void * argument) extern
User Interface. De task wacht op kant en klare user-strings (TaskNotifyTake) van ISR-handler, en interpreteert de string. Het eerste character geeft het hoofd-commando aan. Afhankelijk van het commando worden opvolgende chars geinterpreteerd.
Parameters
*argument Niet gebruikt, eventueel een waarde of string om te testen
Returns
void
0 - 5: Togglet verschillende debug-outputs naar UART
... en reageert ook op een paar letters
D: Verandert de Default OSTIME-DELAY, die gebruikt wordt bij de LEDs. commando: "d,200" betekent: set delay op 200, NB: spaties worden niet afgevangen...
M: Displays het menu (zie my_app.c)
T: Displays de stackdata van alle Tasks
P: Verandert de Prioriteit van een taak commando, als: "t,9,20" betekent: set Task 9 op priority 20
S: Start/Stop task commando, als: "s,9" betekent: start/stop Task 9
Definition at line 134 of file UART_keys.c.
{
    char   *s;
    char   *tok = ",";  // token if command is more than 1 char
    int     val1, val2;
    UART_puts((char *)__func__); UART_puts("started\n\r");
    while (TRUE)
    {
        // wacht op de string; let op de cast van (unsigned long) naar (char *)!
        // want de waarde die ik terug krijg is een pointer.
        s = (char *)ulTaskNotifyTake(pdTRUE, portMAX_DELAY);
        // check het eerste (en vaak enige) karakter van de inkomende command-string
        // toupper() zorgt ervoor dat het eerste karakter hoofdletter wordt, zo hoef ik niet op kleine
        // letters te checken.
        switch (toupper((unsigned char)s[0]))
        {
        default:  UART_puts(s);
                  UART_puts(" (unkown command)\r\n");
                  break;
        case '0': Uart_debug_out = (Uart_debug_out ? DEBUG_OUT_NONE : DEBUG_OUT_ALL);
                  UART_puts("\r\nall debug output = ");
                  UART_puts(Uart_debug_out == DEBUG_OUT_ALL ? "ON\r\n" : "OFF\r\n");
                  // als alle output uitgezet wordt, is het handig om gelijk het menu te laten zien.
                  if (Uart_debug_out == DEBUG_OUT_NONE)
                      DisplayMenu();
                  break;
        case '1': Uart_debug_out ^= LEDS_DEBUG_OUT; // toggle output on/off
                  UART_puts("\r\nleds output = ");
                  UART_puts(Uart_debug_out & LEDS_DEBUG_OUT ? "ON\r\n" : "OFF\r\n");
                  break;
        case '2': Uart_debug_out ^= ARMKEYS_DEBUG_OUT; // toggle output on/off
                  UART_puts("\r\narmkeys output = ");
                  UART_puts(Uart_debug_out & ARMKEYS_DEBUG_OUT ? "ON\r\n" : "OFF\r\n");
                  break;
        case '3': Uart_debug_out ^= UART_DEBUG_OUT; // toggle output on/off
                  UART_puts("\r\nuart output = ");
                  UART_puts(Uart_debug_out & UART_DEBUG_OUT ? "ON\r\n" : "OFF\r\n");
                  break;
        case '4': Uart_debug_out ^= STUDENT_DEBUG_OUT; // toggle output on/off
                  UART_puts("\r\nstudent output = ");
                  UART_puts(Uart_debug_out & STUDENT_DEBUG_OUT ? "ON\r\n" : "OFF\r\n");
                  break;
        case '5': Uart_debug_out ^= GPS_DEBUG_OUT; // toggle output on/off
                  UART_puts("\r\nGPS output = ");
                  UART_puts(Uart_debug_out & GPS_DEBUG_OUT ? "ON\r\n" : "OFF\r\n");
                  break;
        case 'D':
                  os_delay = atoi(s+2); // skip first 2 characters
                  UART_puts("\r\n os_delay set to: "); UART_putint(os_delay);
                  break;
        case 'M': DisplayMenu();
                  break;
        case 'T': DisplayTaskData();
                  break;
        case 'P':
                  //  eerst: de 2 waarden worden uit de string gehaald met strtok()
                  //  dan: de strings worden naar int geconverteerd
                  //  nb. dit is wel grof geprogrammeerd zo, in het echt maak je hier een mooie functie van.
                  s = strtok(s,    tok);                 // naar start van string, negeer 't,'
                  s = strtok(NULL, tok); val1 = atoi(s); // volgende = task_id
                  s = strtok(NULL, tok); val2 = atoi(s); // volgende = priority
                  if (val1 && val2)                      // kleine validiteitscontrole
                      SetTaskPriority(val1, val2);
                  break;
        case 'S':
                  //  eerst: de waarde worden uit de string gehaald met strtok()
                  //  dan: de string wordt naar int geconverteerd
                  //  nb. dit is wel grof geprogrammeerd zo, in het echt maak je hier een mooie functie van.
                  s = strtok(s,    tok);                 // naar start van string, negeer 's,'
                  s = strtok(NULL, tok); val1 = atoi(s); // volgende = task_id
                  if (val1)                      // kleine validiteitscontrole
                      StartStopTask(val1);
                  break;
        case 'X':
                UART_puts("Testing NRF24 SPI communication..., should return 0x08\r\n");
                uint8_t cfg = nrf24_SPI_commscheck();
                char tmp[8];
                snprintf(tmp, sizeof(tmp), "%02X", cfg);   // prints two hex digits
                UART_puts("CONFIG register: 0x"); UART_puts(tmp); UART_puts("\r\n");
                break;
        case 'N': // Print NRF24 debug output
                Uart_debug_out ^= NRF24_DEBUG_OUT; // toggle output on/off
                UART_puts("\r\nNRF24 output = ");
                UART_puts(Uart_debug_out & NRF24_DEBUG_OUT ? "ON\r\n" : "OFF\r\n");
                break;
        }
    }
}
References ARMKEYS_DEBUG_OUT, DEBUG_OUT_ALL, DEBUG_OUT_NONE, DisplayMenu(), DisplayTaskData(), GPS_DEBUG_OUT, LEDS_DEBUG_OUT, NRF24_DEBUG_OUT, nrf24_SPI_commscheck(), os_delay, SetTaskPriority(), StartStopTask(), STUDENT_DEBUG_OUT, TRUE, UART_DEBUG_OUT, and Uart_debug_out.
Variable Documentation
hGPS_Mutex
SemaphoreHandle_t hGPS_Mutex extern
handle voor GPS parser Mutex
Definition at line 52 of file admin.c.
Referenced by CreateHandles(), fill_GNRMC(), and getlatest_GNRMC().
hGPS_Queue
QueueHandle_t hGPS_Queue extern
handle voor GPS-queue
handle voor GPS-queue
Definition at line 48 of file admin.c.
Referenced by CreateHandles(), GPS_getNMEA(), and HAL_UART_RxCpltCallback().
hKEY_Event
EventGroupHandle_t hKEY_Event extern
handle voor ARM-keys-event
Definition at line 50 of file admin.c.
Referenced by ARM_keys_IRQ(), and CreateHandles().
hLED_Sem
SemaphoreHandle_t hLED_Sem extern
handle voor LED-mutex
handle voor LED-mutex
Definition at line 49 of file admin.c.
Referenced by ARM_keys_task(), CreateHandles(), LED_Task1(), LED_Task2(), LED_Task3(), and LED_Task4().
hTimer1
TimerHandle_t hTimer1 extern
handle voor software timer
Definition at line 51 of file admin.c.
Referenced by CreateHandles().
hUART_Queue
QueueHandle_t hUART_Queue extern
typedefs of struct itself and pointer to it
alle handles handle voor UART-queue
Definition at line 47 of file admin.c.
Referenced by CreateHandles(), HAL_UART_RxCpltCallback(), and UART_keys_IRQ().
NRF24_new_value
char NRF24_new_value extern
NRF24 status bits.
NRF24 status bits.
Definition at line 43 of file admin.c.
Referenced by NRF_receive().
Uart_debug_out
int Uart_debug_out extern
default: debug all output to uart
debug naar uart output, zie uart_keys.c bitmask-toggle key voor task-debug-output
Definition at line 40 of file admin.c.
Referenced by ARM_keys_task(), fill_GNRMC(), GPS_getNMEA(), LED_Task1(), LED_Task2(), LED_Task3(), LED_Task4(), NRF_receive(), Student_task1(), UART_keys_IRQ(), UART_keys_poll(), and UART_menu().