GPSlay32: Core/MyApp/App/ARM_keys.c File Reference
ARM_keys.c File Reference
Behandelt de communicatie met de ARM-toetsjes met: Eventgroups, TaskNotify, Interrupt-handling.
Demonstreert: xEventGroupWaitBits(), xTaskGetHandle(), xTaskNotify(), xTaskNotifyWait(),xSemaphoregive(), xSemaphoreTake().
#include <admin.h>
#include "main.h"
#include "cmsis_os.h"
Functions
void ARM_keys_IRQ (void *argument)
Deze task handelt de ARM-toets af, die ontvangen is van de ISR-handler (zie: stm32f4xx_it.c).
void ARM_keys_task (void *argument)
Task krijgt ARM-key met notificatie binnen, en zet ledjes op die waarde. Ook de gekleurde ledjes (behalve blauw, die wordt door de timer gebruikt) krijgen een schwung...
void toggle_led (uint32_t color)
Zet een kleurenledje aan en uit.
Detailed Description
Behandelt de communicatie met de ARM-toetsjes met: Eventgroups, TaskNotify, Interrupt-handling.
Demonstreert: xEventGroupWaitBits(), xTaskGetHandle(), xTaskNotify(), xTaskNotifyWait(),xSemaphoregive(), xSemaphoreTake().
Aan de ARM-keys is een interrupt gekoppeld (zie stm32f4xx_it.c). Die stuurt een event door die opgevangen wordt door task ARM_keys_IRQ().
Author
MSC
Date
5/5/2022
Definition in file ARM_keys.c.
Function Documentation
ARM_keys_IRQ()
void ARM_keys_IRQ (void * argument)
Deze task handelt de ARM-toets af, die ontvangen is van de ISR-handler (zie: stm32f4xx_it.c).
Parameters
*argument Niet gebruikt, eventueel een waarde of string om te testen
Returns
void.
Definition at line 36 of file ARM_keys.c.
{
    unsigned int key;
    osThreadId_t hTask;
    UART_puts("\r\n"); UART_puts((char *)__func__); UART_puts(" started");
    if (!(hTask = xTaskGetHandle("ARM_keys_task")))
        error_HaltOS("Err:ARM_hndle");
    while (1)
    {
        // wait for ISR (EXTI0_IRQHandler()) to signal that a key is pressed
        key = xEventGroupWaitBits(hKEY_Event, 0xffff, pdTRUE, pdFALSE, portMAX_DELAY );
        xTaskNotify(hTask, key, eSetValueWithOverwrite); // notify task2 with value
    }
}
References error_HaltOS(), and hKEY_Event.
ARM_keys_task()
void ARM_keys_task (void * argument)
Task krijgt ARM-key met notificatie binnen, en zet ledjes op die waarde. Ook de gekleurde ledjes (behalve blauw, die wordt door de timer gebruikt) krijgen een schwung...
Parameters
*argument Niet gebruikt, eventueel een waarde of string om te testen.
Returns
void.
Definition at line 63 of file ARM_keys.c.
{
    uint32_t     key;
    int          i, led;
    while(TRUE)
    {
        // WAITING FOR users key
        xTaskNotifyWait (0x00,              // Don't clear any notification bits on entry.
                         0xffffffff,        // ULONG_MAX, reset the notification value to 0 on exit.
                         &key,              // Notified value.
                         portMAX_DELAY);    // Block indefinitely.
        xSemaphoreTake(hLED_Sem, portMAX_DELAY); // krijg toegang (mutex) tot leds
        LED_put((unsigned char)key); // set 8 leds-byte to key-value
        BUZZER_put (500);
        osDelay(500);
        UART_puts("\r\n\tARM_key pressed to leds: "); UART_putint(key);
        if (Uart_debug_out & ARMKEYS_DEBUG_OUT)
        {
            UART_puts("\r\n\tARM_key pressed to leds: "); UART_putint(key);
        }
        xSemaphoreGive(hLED_Sem); // geef toegang (mutex) vrij
        // tot slot, laat de gekleurde ledjes meedoen
        // maar niet blauw, want die is ingezet voor de timer
        // kijk naar de manier waarop de if-elses er uitzien
        for (i=0; i<3; i++)
        {
            led = (i==0 ? LEDRED : (i==1 ? LEDORANGE : LEDGREEN));
            toggle_led(led);
        }
        // Also notify the Route_Setter task so it can act on this key press.
        // Using a direct task notification avoids races that happen when multiple
        // consumers try to read the shared event group bits.
        osThreadId_t hRoute = GetTaskhandle("Route_setter");
        if (hRoute)
        {
            xTaskNotify(hRoute, key, eSetValueWithOverwrite);
        }
        taskYIELD(); // done, force context switch
    }
}
References ARMKEYS_DEBUG_OUT, GetTaskhandle(), hLED_Sem, LEDGREEN, LEDORANGE, LEDRED, toggle_led(), TRUE, and Uart_debug_out.
toggle_led()
void toggle_led (uint32_t color)
Zet een kleurenledje aan en uit.
Parameters
color De kleur.
Returns
void.
Definition at line 23 of file ARM_keys.c.
{
    HAL_GPIO_TogglePin(GPIOD, color);   // turns led on or off
    osDelay(20);
    HAL_GPIO_TogglePin(GPIOD, color);   // turns led on or off
}
Referenced by ARM_keys_task().