GPSlay32: Core/MyApp/App/gps.h File Reference
gps.h File Reference
Data Structures
struct _GNRMC
Typedefs
typedef struct _GNRMC GNRMC
Enumerations
enum NMEA { eGNRMC = 1 , eGPGSA , eGNGGA }
Functions
int checksum_valid (char *string)
void getlatest_GNRMC (GNRMC *dest)
Function that gets a pointer to the latest complete GNRMC data.
int hex2int (char *c)
int hexchar2int (char c)
Typedef Documentation
GNRMC
typedef struct _GNRMC GNRMC
Enumeration Type Documentation
NMEA
enum NMEA
Enumerator
eGNRMC
eGPGSA
eGNGGA
Definition at line 36 of file gps.h.
{
    eGNRMC = 1,
    eGPGSA,
    eGNGGA
};
Function Documentation
checksum_valid()
int checksum_valid (char * string)
Definition at line 241 of file gps.c.
{
    char *checksum_str;
    int checksum, i;
    unsigned char calculated_checksum = 0;
    // Checksum is postcede by *
    if ((checksum_str = strchr(string, '*')))
    {
        *checksum_str = '\0'; // Remove checksum from string
        // Calculate checksum, starting after $ (i = 1)
        for (i = 1; i < strlen(string); i++)
            calculated_checksum = calculated_checksum ^ string[i];
        checksum = hex2int((char *)checksum_str+1);
        //printf("Checksum Str [%s], Checksum %02X, Calculated Checksum %02X\r\n",(char *)checksum_str+1, checksum, calculated_checksum);
        if (checksum == calculated_checksum)
            return (1);
    }
    return (0);
}
References hex2int().
Referenced by GPS_getNMEA().
getlatest_GNRMC()
void getlatest_GNRMC (GNRMC * dest)
Function that gets a pointer to the latest complete GNRMC data.
Parameters
dest pointer of type GNRMC that will be pointing to the latest GNRMC data
Returns
void
Definition at line 31 of file gps.c.
{
    if(xSemaphoreTake(hGPS_Mutex, portMAX_DELAY) == pdTRUE)
    {
        *dest = *frontendBuffer;
        xSemaphoreGive(hGPS_Mutex);
    }
    else
    {
        error_HaltOS("Err:GPS_mutex");
    }
}
References error_HaltOS(), frontendBuffer, and hGPS_Mutex.
Referenced by Route_Setter().
hex2int()
int hex2int (char * c)
Definition at line 216 of file gps.c.
{
    int value;
    value = hexchar2int(c[0]);
    value = value << 4;
    value += hexchar2int(c[1]);
    return value;
}
References hexchar2int().
Referenced by checksum_valid().
hexchar2int()
int hexchar2int (char c)
Definition at line 228 of file gps.c.
{
    if (c >= '0' && c <= '9')
        return (c - '0');
    if (c >= 'A' && c <= 'F')
        return (c - 'A' + 10);
    if (c >= 'a' && c <= 'f')
        return (c - 'a' + 10);
    return (-1);
}
Referenced by hex2int().