GPSlay32: Core/MyApp/App/gps.c File Reference
gps.c File Reference
Behandelt de gps input-strings (NMEA-protocol) van UART1.
Demonstreert: xMessageBufferRead()
Aan UART1 is een interrupt gekoppeld (zie main.c: HAL_UART_RxCpltCallback(), die de inkomende string op een messagebuffer zet, die we hier uitlezen en verwerken.
#include <admin.h>
#include "main.h"
#include "cmsis_os.h"
#include "gps.h"
Functions
int checksum_valid (char *string)
void fill_GNRMC (char *message)
De chars van de binnengekomen GNRMC-string worden in data omgezet, dwz in een GNRMC-struct, mbv strtok(); De struct bevat nu alleen chars - je kunt er ook voor kiezen om gelijk met doubles te werken, die je dan met atof(); omzet.
void getlatest_GNRMC (GNRMC *dest)
Function that gets a pointer to the latest complete GNRMC data.
void GPS_getNMEA (void *argument)
Leest de GPS-NMEA-strings die via de UART via interrupt-handler (HAL_UART_RxCpltCallback) binnenkomen. * De handler zet elk inkomende character gelijk op een queue, die hier uitgelezen wordt. Vervolgens wordt hiervan een GPS-message opgebouwd en verwerkt.
int hex2int (char *c)
int hexchar2int (char c)
Variables
static GNRMC *volatile backendBuffer = &bufferB
static GNRMC bufferA
static GNRMC bufferB
static GNRMC *volatile frontendBuffer = &bufferA
GNRMC gnrmc
Detailed Description
Behandelt de gps input-strings (NMEA-protocol) van UART1.
Demonstreert: xMessageBufferRead()
Aan UART1 is een interrupt gekoppeld (zie main.c: HAL_UART_RxCpltCallback(), die de inkomende string op een messagebuffer zet, die we hier uitlezen en verwerken.
Author
MSC
Date
5/5/2023
Definition in file gps.c.
Function Documentation
checksum_valid()
int checksum_valid (char * string)
Definition at line 241 of file gps.c.
{
    char *checksum_str;
    int checksum, i;
    unsigned char calculated_checksum = 0;
    // Checksum is postcede by *
    if ((checksum_str = strchr(string, '*')))
    {
        *checksum_str = '\0'; // Remove checksum from string
        // Calculate checksum, starting after $ (i = 1)
        for (i = 1; i < strlen(string); i++)
            calculated_checksum = calculated_checksum ^ string[i];
        checksum = hex2int((char *)checksum_str+1);
        //printf("Checksum Str [%s], Checksum %02X, Calculated Checksum %02X\r\n",(char *)checksum_str+1, checksum, calculated_checksum);
        if (checksum == calculated_checksum)
            return (1);
    }
    return (0);
}
References hex2int().
Referenced by GPS_getNMEA().
fill_GNRMC()
void fill_GNRMC (char * message)
De chars van de binnengekomen GNRMC-string worden in data omgezet, dwz in een GNRMC-struct, mbv strtok(); De struct bevat nu alleen chars - je kunt er ook voor kiezen om gelijk met doubles te werken, die je dan met atof(); omzet.
Returns
void
Definition at line 50 of file gps.c.
{
    // example: $GNRMC,164435.000,A,5205.9505,N,00507.0873,E,0.49,21.70,140423,,,A
    //          id    , time     ,s,
    osThreadId_t hTask;
    char *tok = ",";
    char *s;
    GNRMC *localBuffer = backendBuffer;
    memset(localBuffer, 0, sizeof(GNRMC)); // clear the struct
    s = strtok(message, tok); // 0. header;
    strcpy(localBuffer->head, s);
    s = strtok(NULL, tok);    // 1. time; not used
    s = strtok(NULL, tok);    // 2. valid;
    localBuffer->status = s[0];
    s = strtok(NULL, tok);    // 3. latitude;
    strcpy(localBuffer->latitude, s);
    s = strtok(NULL, tok);    // 4. N/S; not used
    s = strtok(NULL, tok);    // 5. longitude;
    if (s[0] == '0') // if leading '0' is present, remove it
        memmove(s, s + 1, strlen(s)); // remove leading '0' if present
    strcpy(localBuffer->longitude, s);
    s = strtok(NULL, tok);    // 6. E/W; not used
    s = strtok(NULL, tok);    // 7. speed;
    strcpy(localBuffer->speed, s);
    s = strtok(NULL, tok);    // 8. course;
    strcpy(localBuffer->course, s);
    if (Uart_debug_out & GPS_DEBUG_OUT)
    {
        UART_puts("\r\n\t GPS type: \t");  UART_puts(gnrmc.head);
        UART_puts("\r\n\t status: \t\t");  UART_putchar(gnrmc.status);
        UART_puts("\r\n\t latitude:\t\t"); UART_puts(gnrmc.latitude);
        UART_puts("\r\n\t longitude:\t");  UART_puts(gnrmc.longitude);
        UART_puts("\r\n\t speed:    \t");  UART_puts(gnrmc.speed);
        UART_puts("\r\n\t course:   \t");  UART_puts(gnrmc.course);
    }
    if(localBuffer->status == 'A'){
        HAL_GPIO_WritePin(GPIOD, LEDGREEN, GPIO_PIN_SET); // GPS fix
    }
    else{
        HAL_GPIO_WritePin(GPIOD, LEDGREEN, GPIO_PIN_RESET); // no GPS fix
    }
    if(xSemaphoreTake(hGPS_Mutex, portMAX_DELAY) == pdTRUE)
    {
        GNRMC *tempbuf = backendBuffer;
        backendBuffer = frontendBuffer;
        frontendBuffer = tempbuf;
        xSemaphoreGive(hGPS_Mutex);
    }
    else
    {
        error_HaltOS("Err:GPS_mutex");
    }
}
References backendBuffer, _GNRMC::course, error_HaltOS(), frontendBuffer, gnrmc, GPS_DEBUG_OUT, _GNRMC::head, hGPS_Mutex, _GNRMC::latitude, LEDGREEN, _GNRMC::longitude, _GNRMC::speed, _GNRMC::status, and Uart_debug_out.
Referenced by GPS_getNMEA().
getlatest_GNRMC()
void getlatest_GNRMC (GNRMC * dest)
Function that gets a pointer to the latest complete GNRMC data.
Parameters
dest pointer of type GNRMC that will be pointing to the latest GNRMC data
Returns
void
Definition at line 31 of file gps.c.
{
    if(xSemaphoreTake(hGPS_Mutex, portMAX_DELAY) == pdTRUE)
    {
        *dest = *frontendBuffer;
        xSemaphoreGive(hGPS_Mutex);
    }
    else
    {
        error_HaltOS("Err:GPS_mutex");
    }
}
References error_HaltOS(), frontendBuffer, and hGPS_Mutex.
Referenced by Route_Setter().
GPS_getNMEA()
void GPS_getNMEA (void * argument)
Leest de GPS-NMEA-strings die via de UART via interrupt-handler (HAL_UART_RxCpltCallback) binnenkomen. * De handler zet elk inkomende character gelijk op een queue, die hier uitgelezen wordt. Vervolgens wordt hiervan een GPS-message opgebouwd en verwerkt.
Returns
void
Definition at line 127 of file gps.c.
{
    char  Q_char;               // char to receive from queue
    char  MSG_buff[GPS_MAXLEN]; // buffer for GPS-string
    int   pos = 0;
    int   cs;                   // checksum-flag
    int   new_msg = FALSE;      // do we encounter a '$'-char?
    int   msg_type = 0;         // do we want this message to be interpreted?
    UART_puts((char *)__func__); UART_puts("started\n\r");
    while (TRUE)
    {
        xQueueReceive(hGPS_Queue, &Q_char, portMAX_DELAY); // get one char from the q
        //UART_putchar(Q_buff);  // echo, for testing
        if (Q_char == '$') // gotcha, new datastring started
        {
            memset(MSG_buff, 0, sizeof(MSG_buff)); // clear buff
            pos = 0;
            new_msg = TRUE; // from now on, chars are valid to receive
        }
        if (new_msg == FALSE) // char only valid if started by $
            continue;
        MSG_buff[pos] = Q_char; // copy char read from Q into the msg-buf
        // if pos==5, the message type (f.i. "$GPGSA) is complete, so we now we can determine
        // if we want the rest of the message... else we skip the rest characters
        if (pos == 5)
        {
            msg_type = 0; // reset
            // next, we decide which message types we want to interpret
            // and we set the message-type for later use...
            if      (!strncmp(&MSG_buff[1], "GNRMC", 5)) msg_type = eGNRMC;
            else if (!strncmp(&MSG_buff[1], "GPGSA", 5)) msg_type = eGPGSA;
            else if (!strncmp(&MSG_buff[1], "GNGGA", 5)) msg_type = eGNGGA;
            if (!msg_type) // not an interesting message type
            {
                new_msg = FALSE;
                continue;
            }
        }
        // if we are here, we are reading the rest of the message into the msg_buff
        if (pos >= GPS_MAXLEN - 1) // avoid overflow (should not happen, but still...)
        {
            new_msg = FALSE; // ignore it
            continue;
        }
        if (MSG_buff[pos] == '\r') // end of message encountered - all messages end with <CR-13><LF-10>
        {
            MSG_buff[pos] = '\0';          // close string
            cs = checksum_valid(MSG_buff); // note, checksumchars (eg "*43") are removed from string
            if (Uart_debug_out & GPS_DEBUG_OUT) // output to uart if wanted
            {
                UART_puts("\r\nGPS (UART4): "); UART_puts(MSG_buff);
                UART_puts( cs ? " [cs:OK]\r\n" : " [cs:ERR]\r\n");
            }
            if (cs) // checksum okay, so interpret the message
            {
                switch(msg_type) // extract data from msg into right struct
                {
                case eGNRMC: fill_GNRMC(MSG_buff);
                             // use the data...
                             break;
                case eGPGSA:
                case eGNGGA: break;
                default:     break;
                }
            }
            new_msg = FALSE; // new message possible
            continue;
        }
        pos++; // proceed reading next char from the queue
    }
}
References checksum_valid(), eGNGGA, eGNRMC, eGPGSA, FALSE, fill_GNRMC(), GPS_DEBUG_OUT, GPS_MAXLEN, hGPS_Queue, TRUE, and Uart_debug_out.
hex2int()
int hex2int (char * c)
Definition at line 216 of file gps.c.
{
    int value;
    value = hexchar2int(c[0]);
    value = value << 4;
    value += hexchar2int(c[1]);
    return value;
}
References hexchar2int().
Referenced by checksum_valid().
hexchar2int()
int hexchar2int (char c)
Definition at line 228 of file gps.c.
{
    if (c >= '0' && c <= '9')
        return (c - '0');
    if (c >= 'A' && c <= 'F')
        return (c - 'A' + 10);
    if (c >= 'a' && c <= 'f')
        return (c - 'a' + 10);
    return (-1);
}
Referenced by hex2int().
Variable Documentation
backendBuffer
GNRMC* volatile backendBuffer = &bufferB static
Definition at line 23 of file gps.c.
Referenced by fill_GNRMC().
bufferA
GNRMC bufferA static
Definition at line 19 of file gps.c.
bufferB
GNRMC bufferB static
Definition at line 20 of file gps.c.
frontendBuffer
GNRMC* volatile frontendBuffer = &bufferA static
Definition at line 22 of file gps.c.
Referenced by fill_GNRMC(), and getlatest_GNRMC().
gnrmc
GNRMC gnrmc
Definition at line 17 of file gps.c.
Referenced by fill_GNRMC().