GPSlay32: Core/MyApp/App/NRF_driver.c File Reference
NRF_driver.c File Reference
Driver voor de NRF24 module in receiver mode. Checkt continu op nieuwe data, en kopieert deze vanuit de module naar een RX buffer.
#include <admin.h>
#include "main.h"
#include "cmsis_os.h"
#include "NRF_driver.h"
#include "NRF24.h"
#include "NRF24_reg_addresses.h"
#include <string.h>
#include "stm32f4xx_hal.h"
#include "NRF24_conf.h"
Macros
#define PLD_SIZE 32
Functions
uint8_t nrf24_SPI_commscheck (void)
void NRF_Driver (void *argument)
Driver for the NRF24 module in receiver mode. Checks continously for new data.
void NRF_receive ()
Receiver function for the NRF24 module in receiver mode. Checks continously for new data and stores in RX buffer.
Variables
uint8_t ack [32]
SPI_HandleTypeDef hspiX
uint8_t rx [32]
Detailed Description
Driver voor de NRF24 module in receiver mode. Checkt continu op nieuwe data, en kopieert deze vanuit de module naar een RX buffer.
Author
Bram Laurens
Version
0.1
Date
2025-10-04
Copyright
Copyright (c) 2025
Definition in file NRF_driver.c.
Macro Definition Documentation
PLD_SIZE
#define PLD_SIZE 32
Definition at line 22 of file NRF_driver.c.
Referenced by NRF_Driver().
Function Documentation
nrf24_SPI_commscheck()
uint8_t nrf24_SPI_commscheck (void)
Definition at line 85 of file NRF_driver.c.
{
    uint8_t tx[2] = {0x00, 0xFF};   // R_REGISTER + CONFIG(0x00), then dummy 0xFF
    uint8_t rx[2] = {0};
    HAL_GPIO_WritePin(csn_gpio_port, csn_gpio_pin, GPIO_PIN_RESET);
    for (volatile int i = 0; i < 50; i++) __NOP();
    HAL_SPI_TransmitReceive(&hspi1, tx, rx, 2, HAL_MAX_DELAY);
    for (volatile int i = 0; i < 50; i++) __NOP();
    HAL_GPIO_WritePin(csn_gpio_port, csn_gpio_pin, GPIO_PIN_SET);
    // rx[0] = STATUS, rx[1] = CONFIG
    return rx[1];
}
References hspi1, and rx.
Referenced by UART_menu().
NRF_Driver()
void NRF_Driver (void * argument)
Driver for the NRF24 module in receiver mode. Checks continously for new data.
Parameters
argument
Definition at line 33 of file NRF_driver.c.
{
    osDelay(100);
    UART_puts((char *)__func__); UART_puts(" started\r\n");
    uint8_t addr[5] = {0xE7, 0xE7, 0xE7, 0xE7, 0xE7};
    HAL_GPIO_WritePin(ce_gpio_port, ce_gpio_pin, 0); // Set CE low
    HAL_GPIO_WritePin(csn_gpio_port, csn_gpio_pin, 1); // Set CSN high
    nrf24_init(); // Initialize NRF24L01+
    nrf24_tx_pwr(_0dbm); // Set TX power to 0dBm
    nrf24_data_rate(_1mbps); // Set data rate to 1Mbps
    nrf24_set_channel(78); // Set channel to 76
    nrf24_pipe_pld_size(0, PLD_SIZE); // Set payload size for pipe 0
    nrf24_set_crc(en_crc, _1byte); // Enable CRC with 1 byte
    nrf24_open_rx_pipe(0, addr); // Open TX pipe with address
    nrf24_pwr_up(); // Power up the NRF24L01+
    while (TRUE)
    {
        NRF_receive();
        osDelay(1); // Placeholder delay
    }
}
References NRF_receive(), PLD_SIZE, and TRUE.
NRF_receive()
void NRF_receive ()
Receiver function for the NRF24 module in receiver mode. Checks continously for new data and stores in RX buffer.
Parameters
argument
Definition at line 65 of file NRF_driver.c.
{
    nrf24_listen(); // Enter listening mode
    if(nrf24_data_available())
    {
        nrf24_receive(rx, sizeof(rx)); // Receive data
        NRF24_new_value = 1; // Set new value flag
    }
    if (Uart_debug_out & NRF24_DEBUG_OUT && NRF24_new_value)
    {
        char msg[50];
        sprintf(msg, rx);
        UART_puts(msg);
        UART_puts("\r\n");
        NRF24_new_value = 0; // Reset new value flag
    }
}
References NRF24_DEBUG_OUT, NRF24_new_value, rx, and Uart_debug_out.
Referenced by NRF_Driver().
Variable Documentation
ack
uint8_t ack[32]
Definition at line 23 of file NRF_driver.c.
hspiX
SPI_HandleTypeDef hspiX extern
rx
uint8_t rx[32]
Definition at line 24 of file NRF_driver.c.
Referenced by nrf24_SPI_commscheck(), and NRF_receive().